"use client";

import { FormEvent, useState } from "react";
import { brandLockup } from "./brand";
import { founderImage, theatreImage } from "./media";
import { BuildLab, CarterCore, CinematicSequence, Reveal, TiltCard } from "./components/immersive-studio";

const email = "hello@carterdigitals.co.za";
const services = [
  ["01", "Signature Websites", "POSITIONING + CONVERSION", "High-end websites that make the offer clear, the brand credible and the next action easy to take.", "card-site"],
  ["02", "Lead Experiences", "FUNNELS + ENQUIRIES", "Landing journeys that turn attention into calls, bookings and qualified conversations.", "card-leads"],
  ["03", "Web Applications", "PRODUCT + PLATFORM", "Portals, dashboards and applications designed around real users and operating needs.", "card-app"],
  ["04", "Automation Systems", "WORKFLOW + FOLLOW-UP", "Practical systems that help teams respond faster and protect valuable opportunities.", "card-flow"],
  ["05", "Dashboards & Tools", "VISIBILITY + DECISIONS", "Business tools that turn activity into insight and insight into action.", "card-data"],
  ["06", "AI-Ready Growth", "MODERN ADVANTAGE", "AI-enabled experiences and cloud-ready foundations for businesses ready to operate smarter.", "card-ai"],
] as const;
const industries = [
  ["Professional services", "Make expertise feel immediately credible.", "Authority-led messaging · High-trust enquiries · Premium client journey"],
  ["Healthcare & wellness", "Give patients a calmer, clearer next step.", "Mobile-first booking · Trust-building content · Clear service paths"],
  ["Education & training", "Make enrolment feel structured and achievable.", "Programme discovery · Learner-ready information · Admissions flow"],
  ["Property & logistics", "Bring moving parts into one clear experience.", "Lead systems · Operations dashboards · Customer access"],
] as const;
type Brief = { name: string; business: string; project: string; goal: string; message: string };

export function HomeExperience() {
  const [sector, setSector] = useState(0);
  const [open, setOpen] = useState(false);
  const [brief, setBrief] = useState<Brief>({ name: "", business: "", project: "Signature website", goal: "More qualified leads", message: "" });
  const start = (project?: string) => { if (project) setBrief((value) => ({ ...value, project })); setOpen(true); };
  const send = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = `Hello Carter Digitals,\n\nName: ${brief.name}\nBusiness: ${brief.business}\nBuild: ${brief.project}\nGoal: ${brief.goal}\n\nContext: ${brief.message}\n\nI would like to start a Carter Build conversation.`; window.location.href = `mailto:${email}?subject=${encodeURIComponent(`Carter Build Enquiry — ${brief.business || brief.name || "New project"}`)}&body=${encodeURIComponent(body)}`; };
  const current = industries[sector];

  return <main>
    <div className="announcement"><div className="shell"><span><i /> FOUNDER-LED DIGITAL DELIVERY</span><p>Premium websites, applications and systems for businesses ready to become impossible to overlook.</p><button onClick={() => start()}>Start a build <b>↗</b></button></div></div>
    <nav className="nav shell"><a className="brand" href="#top"><img src={brandLockup} alt="Carter Digitals" /></a><div className="nav-links"><a href="#theatre">Theatre</a><a href="#services">Capabilities</a><a href="#studio">Founder</a><a href="#method">Method</a></div><button className="nav-button" onClick={() => start()}>Start a project <b>↗</b></button></nav>
    <section className="hero hero--immersive" id="top"><div className="hero-grid" /><div className="hero-noise" /><div className="shell hero-layout hero-layout--immersive"><Reveal className="hero-copy hero-copy--immersive"><p className="eyebrow"><i /> PRETORIA-BASED · SOUTH AFRICA-READY</p><h1>Make your business feel like the <em>future</em> it is working toward.</h1><p className="lead">Carter Digitals designs premium websites, web applications and intelligent business systems for companies that want to be easier to trust, easier to choose and harder to forget.</p><div className="hero-actions"><button className="button button-primary magnetic" onClick={() => start()}>Build my digital advantage <span>↗</span></button><a className="button button-soft" href="#theatre">Enter the digital theatre <span>↓</span></a></div><div className="hero-proof"><span><b>Founder-led</b> strategy and build</span><span><b>Custom</b> — never template-first</span><span><b>Built for</b> mobile-first customers</span></div></Reveal><Reveal className="hero-core-wrap"><CarterCore /></Reveal></div></section>
    <section className="motion-strip"><div className="motion-track"><span>CARTER DIGITALS</span><i>✦</i><span>STRATEGY THAT MOVES</span><i>✦</i><span>DESIGN THAT CONVERTS</span><i>✦</i><span>SYSTEMS THAT SCALE</span><i>✦</i><span>CARTER DIGITALS</span><i>✦</i><span>STRATEGY THAT MOVES</span></div></section>
    <div id="theatre"><CinematicSequence image={theatreImage} /></div>
    <section className="shell studio-section section" id="studio"><Reveal className="studio-card"><div className="studio-mark founder-mark"><div className="studio-halo" /><img src={founderImage} alt="Kabelo Kadiaka, founder of Carter Digitals" /><div className="founder-plaque"><span>KABELO KADIAKA</span><b>FOUNDER / CARTER DIGITALS</b></div><span>KK / FOUNDER</span></div><div className="studio-copy"><p className="eyebrow">THE FOUNDER BEHIND THE BUILD</p><h2>Led by Kabelo Kadiaka. Built for the moment a business decides it is ready to <em>level up.</em></h2><p className="studio-lead">Carter Digitals is a founder-led digital studio based in Pretoria, focused on turning business potential into premium, practical digital experiences.</p><p>Kabelo connects the strategy, customer journey, visual direction and development work so the final product feels intentional from the first screen to the system behind it.</p><div className="studio-signals"><span><b>01</b> Strategy and development stay connected</span><span><b>02</b> Every interaction needs a business reason</span><span><b>03</b> Built to expand when the opportunity does</span></div><button className="text-cta" onClick={() => start()}>Work directly with Kabelo <b>→</b></button></div></Reveal></section>
    <section className="shell capabilities section" id="services"><Reveal><p className="eyebrow">CAPABILITIES WITH CONSEQUENCE</p><div className="heading-row"><h2>Not just a polished interface. A digital asset designed to create <em>momentum.</em></h2><p>The best-looking build means little if it cannot make a business clearer, more credible, more responsive or more valuable to customers.</p></div></Reveal><div className="services-grid services-grid--immersive">{services.map(([number, title, label, copy, className], index) => <TiltCard className={`service-card ${className}`} key={title}><div className="service-meta"><span>{number}</span><small>{label}</small></div><h3>{title}</h3><p>{copy}</p><button className="card-arrow" onClick={() => start(title)}>Explore <b>↗</b></button><div className="card-visual">{index === 0 && <><i /><i /><i /></>}{index === 1 && <><strong>NEW<br />LEAD</strong><span>High-intent<br />enquiry</span></>}{index === 2 && <><b>APP</b><em>01</em><em>02</em></>}{index === 3 && <><span>Lead</span><i>→</i><span>Follow up</span><i>→</i><span>Booked</span></>}{index === 4 && <svg viewBox="0 0 200 90"><path d="M6 76C30 59 44 65 61 53S92 70 112 34S147 59 167 19S187 27 196 7" fill="none" stroke="currentColor" strokeWidth="4" /></svg>}{index === 5 && <><b>AI</b><span>Assist</span><span>Analyse</span><span>Act</span></>}</div></TiltCard>)}</div></section>
    <section className="shell lab-shell section"><Reveal><BuildLab onStart={start} /></Reveal></section>
    <section className="shell promise-section section"><Reveal className="promise-layout"><div><p className="eyebrow">THE CARTER STANDARD</p><h2>A serious digital build should improve more than how the business <em>looks.</em></h2></div><div className="promise-list"><article><span>✦</span><div><h3>A sharper reason to choose you</h3><p>Messaging, proof and visual framing that help the right customer recognise the value.</p></div></article><article><span>✦</span><div><h3>A more confident path to action</h3><p>Calls, bookings and enquiry journeys that make the next step feel natural.</p></div></article><article><span>✦</span><div><h3>A better operating foundation</h3><p>Flexible systems ready for automation, analytics, client access and future products.</p></div></article></div></Reveal></section>
    <section className="shell industry-section section" id="industries"><Reveal><p className="eyebrow">BUILT AROUND REAL BUSINESS CONTEXT</p><div className="heading-row"><h2>Different industries need different proof, journeys and systems.</h2><p>Carter starts with the decision a customer needs to make, then builds the experience around helping them make it confidently.</p></div></Reveal><Reveal className="industry-map industry-map--premium"><div className="industry-tabs">{industries.map(([name], index) => <button key={name} className={sector === index ? "selected" : ""} onClick={() => setSector(index)}><span>0{index + 1}</span>{name}<b>↗</b></button>)}</div><div className="industry-content"><div className="industry-number">0{sector + 1}</div><p className="eyebrow">{current[0]}</p><h3>{current[1]}</h3><p>{current[2]}</p><button className="button button-dark" onClick={() => start(`${current[0]} digital experience`)}>Build for this business <b>↗</b></button></div></Reveal></section>
    <section className="impact-section"><div className="shell"><Reveal><div className="impact-heading"><p className="eyebrow light">THE DIFFERENCE IN THE DETAILS</p><h2>Every layer should make the next step feel more <em>inevitable.</em></h2></div><div className="impact-grid"><article><span>01</span><h3>Immersive, but intentional</h3><p>Motion and 3D depth catch attention. Strong hierarchy and direct copy turn attention into understanding.</p><b>Experience design</b></article><article><span>02</span><h3>Premium, but practical</h3><p>The polish earns trust, while the technical choices stay responsive and ready to evolve.</p><b>Product thinking</b></article><article><span>03</span><h3>Bold, but business-first</h3><p>Every interaction should give the customer a clearer reason to move closer to the business.</p><b>Conversion architecture</b></article></div></Reveal></div></section>
    <section className="shell process process--premium section" id="method"><Reveal><p className="eyebrow">THE CARTER BUILD METHOD</p><div className="heading-row"><h2>Clear thinking. Premium execution. A visible path from idea to <em>launch.</em></h2><p>You always know the role of the next stage and how the work is moving the business forward.</p></div><div className="process-grid">{[["01", "Clarify", "The goal, the audience and the story that has to land first."], ["02", "Architect", "A product structure built around a clear customer journey."], ["03", "Design", "A visual language that earns attention and makes the business feel ready."], ["04", "Build", "Founder-led engineering with responsive, reusable foundations."], ["05", "Launch + evolve", "A confident release and room for the next opportunity."]].map(([number, title, copy]) => <article key={number}><span>{number}</span><i /><h3>{title}</h3><p>{copy}</p></article>)}</div></Reveal></section>
    <section className="final final--immersive"><div className="final-grid" /><div className="final-glow" /><div className="shell"><Reveal><div className="final-logo"><img src={brandLockup} alt="Carter Digitals" /></div><p className="eyebrow light">START A CARTER BUILD</p><h2>Your next chapter deserves a digital experience that looks and feels <em>ready.</em></h2><p>Bring the idea, the outdated website, the operational problem or the opportunity you can already see. Carter Digitals will help turn it into a digital asset built to create momentum.</p><div className="hero-actions"><button className="button button-primary" onClick={() => start()}>Start my project brief <span>↗</span></button><a className="button button-outline" href={`mailto:${email}`}>Email Carter Digitals</a></div><footer><span>© 2026 CARTER DIGITALS</span><span>FOUNDER: KABELO KADIAKA</span><span>PRETORIA · GAUTENG · SOUTH AFRICA</span></footer></Reveal></div></section>
    {open && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Start a Carter Build"><form className="project-modal" onSubmit={send}><button className="close" type="button" onClick={() => setOpen(false)}>×</button><div className="project-modal-heading"><p className="eyebrow">START A CARTER BUILD</p><h2>Tell us what the next version of your business needs to do.</h2><p>This short brief gives Kabelo enough context to make the first conversation useful.</p></div><div className="brief-grid"><label>YOUR NAME<input required value={brief.name} onChange={(event) => setBrief({ ...brief, name: event.target.value })} placeholder="Your name" /></label><label>BUSINESS / BRAND<input required value={brief.business} onChange={(event) => setBrief({ ...brief, business: event.target.value })} placeholder="Business name" /></label><label>WHAT DO YOU WANT TO BUILD?<select value={brief.project} onChange={(event) => setBrief({ ...brief, project: event.target.value })}><option>Signature website</option><option>Lead-generation landing experience</option><option>Client portal or web application</option><option>Internal system or dashboard</option><option>AI or workflow automation</option><option>Digital product / MVP</option></select></label><label>WHAT MATTERS MOST?<select value={brief.goal} onChange={(event) => setBrief({ ...brief, goal: event.target.value })}><option>More qualified leads</option><option>Premium brand perception</option><option>Better customer experience</option><option>Less operational friction</option><option>Launch a digital product</option></select></label><label className="brief-message">PROJECT CONTEXT<textarea value={brief.message} onChange={(event) => setBrief({ ...brief, message: event.target.value })} placeholder="What is changing? What is not working now? What would success look like?" rows={5} /></label></div><div className="brief-footer"><p>Your details open a pre-filled email. You stay in control of sending it.</p><button className="button button-primary" type="submit">Open my project email <span>↗</span></button></div></form></div>}
  </main>;
}
